### ISSUE TITLE
使用我的代码麻烦标注一下原作者好吧

### ISSUE THREAD

**Issue by xgugugu** [WP-Studio01/freedom#11]
使用我的代码麻烦标注一下原作者

我记得我原来的仓库是用的GPLv2许可证

基于我源代码的所有项目都必须用GPLv2及以上的许可证

**Comment by WP-Studio01** [comment]
我不会



在 2022-11-13 15:44:24，"xgugugu" ***@***.***> 写道：

使用我的代码麻烦标注一下原作者

我记得我原来的仓库是用的GPLv2许可证

基于我源代码的所有项目都必须用GPLv2及以上的许可证

**Comment by xgugugu** [comment]
> 我不会 在 2022-11-13 15:44:24，"xgugugu" ***@***.***> 写道： 使用我的代码麻烦标注一下原作者 我记得我原来的仓库是用的GPLv2许可证 基于我源代码的所有项目都必须用GPLv2及以上的许可证 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

标注在readme.md里

其实用MIT许可证也行

反正我也不更新了
