### ISSUE TITLE
发个图片试试

### ISSUE THREAD

**Issue by codejiangqihan** [WP-Studio01/freedom#4]
![icon](https://user-images.githubusercontent.com/107793872/200283179-a5a00e16-fbe8-4b85-95aa-e4b417c573e0.png)
![image](https://user-images.githubusercontent.com/107793872/200283306-e61d088a-2cf2-44c5-98bb-c323dc6fc0bc.png)
![image](https://user-images.githubusercontent.com/107793872/200283377-348e4311-8ecf-4a2c-9f61-4060d01a94ee.png)
![image](https://user-images.githubusercontent.com/107793872/200283497-abd48d5d-524f-41fb-a66e-a10cc7cd5d30.png)
![image](https://user-images.githubusercontent.com/107793872/200283557-e2c5af54-e16e-45f4-b69a-661c287e23d4.png)

**Comment by WP-Studio01** [comment]
《Goooooooooogle》

**Comment by WP-Studio01** [comment]
请不要再灌水了好吗，灌水贴我已经关闭了

**Comment by codejiangqihan** [comment]
> 请不要再灌水了好吗，灌水贴我已经关闭了

我本来是想推荐一下这个论坛的，你这样我就不推荐了，哪有论坛不让人发东西的

**Comment by WP-Studio01** [comment]
太灌水了



在 2022-11-08 18:45:27，"codejiangqihan" ***@***.***> 写道：

请不要再灌水了好吗，灌水贴我已经关闭了

我本来是想推荐一下这个论坛的，你这样我就不推荐了，哪有论坛不让人发东西的
